### ISSUE TITLE
Add tabs to info panel

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/bil-map#10]
More content will be added to this info panel and would be nice to organize as tabs (with next/previous buttons too). Quick browser mockup:

<img width="389" alt="Screen Shot 2020-04-25 at 1 48 08 PM" src="https://user-images.githubusercontent.com/33635008/80286834-c0560e80-86fb-11ea-92fb-09d4518d62a5.png">

**Comment by hoshmn** [comment]
added with 89f74be474c8839733743675efe6d7f1d539c791
