### ISSUE TITLE
Add intro panel

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/bil-map#2]
Create intro panel at left of map that will contain the text

> Map of Universal Basic Income Experiments and Related Programs
> 
> How and where have Universal Basic Income (UBI) and its cousin policies been tested? What are some significant differences between these programs and which features do they share with an ideal UBI policy? What impacts can be measured when giving individuals unconditional cash on a regular basis? This geospatial map presents UBI-related experiments, pilots, programs and policies throughout the world, some past and some ongoing, and enables the user to compare them across a range of design and implementation features. It sheds light on many basic income related experiments over the past 60 years in order to inform the current dialogue around a potential basic income policy in the United States and beyond. 
> 
> INCLUSION CRITERIA
> 
> The map contains experiments, pilots, policies and programs that have design and implementation features that crossover with the key principles of a universal basic income: unconditional, universal, regular, individual, and paid in cash. 
> 
> As described in the review of the State of the Evidence on Universal Basic Income-type programs: An Umbrella Review (Hasdell, forthcoming), experiments recognized as pertinent to UBI research  are varied and can be classified into different types of cash transfer programs ranging from unconditional and universal cash to supplemental income schemes to resource dividends and minimum income guarantees (through a negative income tax). 
> 
> The experiments, pilots, policies and programs we have included in this geospatial map all share multiple of the aforementioned features of a universal basic income policy and are frequently cited in the basic income literature used to infer potential impacts of a basic income policy (see Hoynes and Rothstein, 2019; Gentilini et. al, 2019, and Banerjee et. al, 2019; and Gibson et. al, 2018).  
>
> The Basic Income Lab included these experiments for this current version. Over time, we hope to add more experiments as they come to light.

Would be great to have this as a panel on left side that a) is fixed-height and scrollable within, to accommodate all this text, and b) can be collapsed leftward, and when collapsed, there could be a small tab to re-expand, perhaps with the standard “i” info icon (https://www.google.com/search?q=info+icon&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiekM7J6O3oAhWVaM0KHV5WA9gQ_AUoAXoECBcQAw&biw=1263&bih=749)

**Comment by hoshmn** [comment]
@james-minton checkout what I did and see what you think. On mobile I have it covering most of the screen (besides legend), since you couldn't really have it open and do anything meaningful with the map. Right now it defaults to open, but seems like starting closed would be better. Thoughts?
