### ISSUE TITLE
Add "data current through" to legend

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/bil-map#23]
If possible, use google sheet's "last updated" date to populate a note at the bottom of the legend:

"Data current through [date]"

If not possible to get the last updated date automatically from the sheet, let's discuss other ways to supply this data.

**Comment by coreytegeler** [comment]
There's no date in the JSON but I just manually added it in the `A1` cell to test. They can decide to put it wherever as long as it's consistent.
