### ISSUE TITLE
Small functionality changes

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/bil-map#3]
Adding these minor fixes as needed here on ongoing basis, rather than making a ton of issues:

- [x] Make “only 3 cards viewable” hinting timeout last longer; am concerned it may be too fast for some users. Optional: make it dismissible with an “x” -- we have both a timeout and the option to dismiss for the same hint on EL's map. Not sure if it's necessary here.

**Comment by hoshmn** [comment]
>     * [x]  Make “only 3 cards viewable” hinting timeout last longer; am concerned it may be too fast for some users. Optional: make it dismissible with an “x” -- we have both a timeout and the option to dismiss for the same hint on EL's map. Not sure if it's necessary here.

Resolved with 4addfb8d8a045f7d6d8e4562e23065b8fee5c922 gave it an X to manually dismiss, auto-dismisses after 30s.
