### ISSUE TITLE
Reflect active pilots by country

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/bil-map#34]
Show number of pilots per country (not state/territory, etc.) on the map. See mockup below and [in Figma here](https://www.figma.com/file/YlxU0ZV5pVgEXHNsHsR80w/BIL-MAP-mockups?node-id=695%3A69&t=q02w5sFavpYDdRS8-1).

### UI updates

On hover of a given country:

- Show country outline (2px line, #709FAC) and overlay (same color, 2% opacity)
- Tooltip shows country name and number of total number of experiments. This number should change based on filtering.

![Number of pilots per country](https://user-images.githubusercontent.com/33635008/202288219-dfc5f66a-8ea8-44ba-964e-db55ed22cb83.png)

**Comment by james-minton** [comment]
Hi @reefdog, wonder what you think of the implementation idea above, for the "show experiment totals by country" feature request?

**Comment by reefdog** [comment]
@james-minton I think it's fairly good and can certainly try to implement as-is. Are you envisioning it hovering some # of pixels above (or below, as space requires) the cursor and tracking with it?

One alternative to an interaction would be to put the experiment count below the static country label rather than as a tooltip. (Similarly styled as a smaller font-size and lighter font-weight.) If always seeing the count is too noisy, then perhaps only display it on hover, but still statically-positioned below the existing country label. Thoughts?

**Comment by reefdog** [comment]
Ooh, great thoughts. I failed to consider that these labels were from the underlying Mapbox labels. We might still be able to get there, I'll explore it.

> Probably a better option would be to show it (at all zoom levels) only for countries that have experiments; that would deal with the problem of overcluttering.

I like this and would start here. I think the additional text is lightweight enough that the general Mapbox math for when to show the country name is sufficient for when to show this label, too. (I.e., we'll show the experiment count anytime the count is greater than zero and Mapbox determines we;re at an appropriate zoom level to show the country name.)

**Comment by reefdog** [comment]
If we _can't_ piggyback on the Mapbox labels this way, or do a samizdat version of that by anchoring the count to the label and following the zoom level display logic, then I'll go back to the tooltip idea.

**Comment by reefdog** [comment]
I've been playing around with this a little bit, and the good news is: we are definitely able to supplement Mapbox's labels with our own! The syntax for doing so is convoluted, though, so before I go much further into whack-a-mole'ing the little issues I'm finding, let's be sure we like this:

<img width="1560" alt="image" src="https://user-images.githubusercontent.com/4731/204920984-b92c9af5-c553-4247-9890-e001f860cac0.png">

- We can style the text however we want; I just went smaller and grayer.
- We can limit the labels to only showing up when the country has experiments.
- We will probably need to change the spreadsheet's `country` column to conform to some standard naming convention that matches the internal dictionary of Mapbox countries. This can be a standard English name, e.g. `Canada` (so long as it matches Mapbox's), or preferably the [ISO 3166-1 country code](https://en.wikipedia.org/wiki/ISO_3166-1), e.g. `CA`. If we can't change that column, then we'll need to add a column (like `participants_number`) for this purpose.
- I'm seeing a little unexpected behavior w/r/t when labels show up and where. It seems only US and Canada currently appear, and that both decompose into states at a certain zoom level. We should discuss if we want this same behavior, and also if we want to also append site counts to _state_ names as well. (I feel this would be a bit noisy.)

**Comment by james-minton** [comment]
Thanks @reefdog, this is all great --

- agree on everything, including not showing totals for smaller geographies like states
- only question is whether the experiment numbers for each country should update after filtering, or not. We are showing post-filtering totals via "displaying [ number ] experiment sites" in the legend, but that's for all countries.
  - leaning toward not updating this number after filtering, and consistently saying "100 _total_ experiment sites" or something. Feels like changing it via filters carries potential for confusion. But I can check this with client tomorrow.

**Comment by james-minton** [comment]
(We could display both total and filtered numbers per country, but that seems like it has the potential to get too busy. Almost would prefer to go back to a tooltip if we did that.)

**Comment by james-minton** [comment]
@reefdog client liked this idea; use case seems to be that people want to see total + active counts (independent of filters) per country. I wonder if a string like

`[number] sites, [number] active`

wouldn't be too busy? Using a light weight for this could help.

![Screen Shot 2022-12-02 at 4 43 56 PM](https://user-images.githubusercontent.com/33635008/205395447-9b4d994a-b2a6-4543-831a-7e9444340e5c.png)

**Comment by reefdog** [comment]
@reefdog Should be doable. Something about the comma feels a bit more literary than UI-native to me. What about `100 sites (84 active)`? Or are parentheses even worse? I think I just like how it implies a subset. Your call of course.

**Comment by reefdog** [comment]
@james-minton Also, your earlier point about possible confusion of the numbers after filtering is well-taken. 🤔 I think the easiest thing is (as you suggested) to have the labels _not_ change as the filter does. Maybe we start there and iterate if it feels like it needs it?

**Comment by james-minton** [comment]
@reefdog parentheses sounds good, and yeah, client does not feel filters should be reflected here either so I think we can leave it at that.

**Comment by reefdog** [comment]
@james-minton Implemented that one and I think it is the best option! I did iterate through a few other styles just in case, but I expect you'll want to stick with option A:

<img alt="sample-a" src="https://user-images.githubusercontent.com/4731/205764100-1374191d-026d-438b-80ec-b3e217bf08d5.jpeg" width="400" height="auto">
<img alt="sample-b" src="https://user-images.githubusercontent.com/4731/205762417-69cf72b3-7e2c-4fdc-a553-4b32c909eabb.jpeg" width="400" height="auto">
<img alt="sample-c" src="https://user-images.githubusercontent.com/4731/205762418-cf0847f6-b0ac-4aa9-9166-d8b69e9832c9.jpeg" width="400" height="auto">
<img alt="sample-d" src="https://user-images.githubusercontent.com/4731/205762420-f035169f-6ba2-4e5a-a6dc-4fc4fef9e7e6.jpeg" width="400" height="auto">
