### ISSUE TITLE
Allow csv export of all experiments

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/bil-map#41]
Use existing export functionality for selected experiments to allow users to download all experiments.

Front end:

Create a modal, triggered by the "export" button, with radio buttons for "Export selected experiments" and "Export all experiments."

**Comment by reefdog** [comment]
You noted in Slack that using the existing export interface for exporting all means that the user has to take a pretty circuitous path to get to Export All: select sites (that they may not care about), scroll down, click Export, and (with the addition of this modal) click Export All. I think users may have trouble discovering this flow.

If we do keep the current interface for now, I do wonder if we could at least replace the modal idea with simply a second Export button below the current one? Kind of like how we have the Twitter/Facebook buttons below the Copy button/field on the Share section:

<img width="210" alt="Export interface for BIL map" src="https://user-images.githubusercontent.com/4731/204887365-0a894782-1a8b-4ae0-bf96-5f7ce0bd56e7.png">

Though I would recommend doing some further tweaks to styling and language.

**Comment by james-minton** [comment]
I think if you/we end up having enough spare capacity, we could revisit the UI as you propose. (It will involve some UI design and back-and-forth, and I may be a little stretched in that regard over the coming weeks, FYI.)

For now, since 

- exporting csv's is such a niche use case and a given user might only do it one time
- users who are motivated to drill into the data will probably be clicking on experiments, comparing, and scrolling down, thus discovering the export feature

I think it's okay (if suboptimal) to let it be a progressively-disclosed feature at the bottom.

I like your two-button solution better than a modal; let's do that.

**Comment by reefdog** [comment]
Sounds good, on it!
