### ISSUE TITLE
Embed map in shell site

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/bil-map#6]
Set up testing branch, wrap map into /research/basic-income-experiments/ (replacing existing table).

**Comment by james-minton** [comment]
Existing photo hero can go; maybe leave the subnav for now and we'll make a call later on whether it stays or goes.

**Comment by hoshmn** [comment]
I have this working locally with [this commit](https://github.com/Hyperobjekt/bil-site/commit/2e3c73eef05282222c7c570b6d3d79167e9ea25e) to an iframe-map branch of the bil-site
[video](https://drive.google.com/file/d/1a2GcXADyUld9O0xiJqYfC8saooI-sXQl/view)
