### ISSUE TITLE
Disable mouse zoom on map until cards are fully docked, add scroll-to-top button

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/bil-map#9]
1. For reference, go to [here](https://evictionlab.org/map/#/2016?geography=states&type=er&locations=20,-98.322,38.502%2B08,-105.557,38.999%2B35,-106.107,34.426) and scroll down, then scroll back up. You can see map access is disabled until scroll returns the window fully to the top.

Something like this would be very useful here, because sometimes attempting to scroll back up to the top from the cards display will trigger map zoom, depending on mouse position.

2. Scroll to top button might be nice, appearing after a certain scroll position? These tables get to be pretty long. E.g. scroll down on [Rankings](https://evictionlab.org/rankings/#/evictions?r=United%20States&a=0&d=evictionRate&lang=en) or [here](https://evictionlab.org/covid-policy-scorecard/) to see the button that appears.

**Comment by hoshmn** [comment]
part 1 merged with 7bb672b7664cc385d7b7d9b72e7a05636a34daf9

**Comment by hoshmn** [comment]
have a look, feel free to play with styles. arrow will face right for now until we resolve #13
